genewvectorresource -o Resources/Vector/Roads/TigerLine2009/ALABAMA --filelist ALABAMA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/ALASKA --filelist ALASKA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/ARIZONA --filelist ARIZONA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/ARKANSAS --filelist ARKANSAS_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/CALIFORNIA --filelist CALIFORNIA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/COLORADO --filelist COLORADO_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/CONNECTICUT --filelist CONNECTICUT_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/DELAWARE --filelist DELAWARE_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/DISTRICT_OF_COLUMBIA --filelist DISTRICT_OF_COLUMBIA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/FLORIDA --filelist FLORIDA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/GEORGIA --filelist GEORGIA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/HAWAII --filelist HAWAII_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/IDAHO --filelist IDAHO_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/ILLINOIS --filelist ILLINOIS_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/INDIANA --filelist INDIANA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/IOWA --filelist IOWA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/KANSAS --filelist KANSAS_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/KENTUCKY --filelist KENTUCKY_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/LOUISIANA --filelist LOUISIANA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MAINE --filelist MAINE_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MARYLAND --filelist MARYLAND_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MASSACHUSETTS --filelist MASSACHUSETTS_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MICHIGAN --filelist MICHIGAN_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MINNESOTA --filelist MINNESOTA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MISSISSIPPI --filelist MISSISSIPPI_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MISSOURI --filelist MISSOURI_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/MONTANA --filelist MONTANA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NEBRASKA --filelist NEBRASKA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NEVADA --filelist NEVADA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NEW_HAMPSHIRE --filelist NEW_HAMPSHIRE_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NEW_JERSEY --filelist NEW_JERSEY_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NEW_MEXICO --filelist NEW_MEXICO_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NEW_YORK --filelist NEW_YORK_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NORTH_CAROLINA --filelist NORTH_CAROLINA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/NORTH_DAKOTA --filelist NORTH_DAKOTA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/OHIO --filelist OHIO_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/OKLAHOMA --filelist OKLAHOMA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/OREGON --filelist OREGON_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/PENNSYLVANIA --filelist PENNSYLVANIA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/RHODE_ISLAND --filelist RHODE_ISLAND_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/SOUTH_CAROLINA --filelist SOUTH_CAROLINA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/SOUTH_DAKOTA --filelist SOUTH_DAKOTA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/TENNESSEE --filelist TENNESSEE_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/TEXAS --filelist TEXAS_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/UTAH --filelist UTAH_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/VERMONT --filelist VERMONT_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/VIRGINIA --filelist VIRGINIA_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/WASHINGTON --filelist WASHINGTON_filelist
genewvectorresource -o Resources/Vector/Roads/TigerLine2009/WEST_VIRGINIA --filelist WEST_VIRGINIA_filelist
